language: perl6
perl6:
  - latest
install:
  - rakudobrew build-zef
  - zef --debug --depsonly --/test install .
script:
  - RAKULIB=$PWD/lib zef build .
  - RAKULIB=$PWD/lib prove -e perl6 -vr t/
sudo: false
